# -*- coding: utf-8 -*-
"""DSA_major_project_linked_list_library_management_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTyCLM1dan9mQf7cEnJJeRsxqa6rHa0k
"""

class Node():
  def __init__(self,book_name):
    self.book_name=book_name
    self.next=None
class LinkedList():
  def __init__(self):
    self.head=None
  def add(self):
    if(self.head==None):
      book=input("Enter book name: ")
      self.head=Node(book.lower())
    else:
      temp=self.head
      while(temp.next!=None):
        temp=temp.next
      book=input("Enter book name: ")
      temp.next=Node(book.lower())
  def issue(self):
    if(self.head==None):
      print("There is no book in the library rightnow!")
    else:
      choice=int(input("Enter\n 1.if you want to take all the books of the library.\n2.if you want to take a specific book from the library\n"))
      if(choice==1):
        self.head=None
        print("\nAll books have been issued now.\n")
      elif(choice==2):
        book=input("Enter book name you wanna issue: ")
        if(self.head.book_name==book.lower()):
          self.head=self.head.next
          print("The book is successfully issued now.")
        else:
          temp=self.head.next
          prev=self.head
          while temp!=None and temp.book_name!=book.lower():
            prev=prev.next
            temp=temp.next
          if(temp==None):
              print("There is no such book in the library.")
          else:
            prev.next=temp.next
            temp.next=None
            print("The book is successfully issued now.")
      else:
        print("Invalid choice")
  def search(self):
    book=input("Enter book name you wanna search: ")
    temp=self.head
    if(self.head!=None and self.head.book_name==book.lower()):
      print("Yes the book you searched for is present here.\n")
    elif(self.head.next!=None):
      while( temp!=None and temp.book_name!=book.lower() ):
        temp=temp.next
        if(temp==None):
          print("There is no such book in the library rightnow.")
          break

      if(temp!=None and temp.book_name==book.lower()):
        print("Yes the book you searched for is present here.\n")
    elif(self.head==None):
      print("There is no book in the library rightnow.")
  def display(self):
    temp=self.head
    i=0
    if(self.head==None):
      print("\nThere is no book here in the library rightnow.\n")
    while(temp!=None):
      i+=1
      print("\n",i,".", temp.book_name ,"\n")
      temp=temp.next
ll=LinkedList()
while(True):
  user_input=int(input("Enter your choice: \n1.add\n2.issue\n3.search\n4.display\n"))
  try:
    if user_input==1:
      ll.add()
      print("\n")
    elif user_input==2:
      ll.issue()
      print("\n")
    elif user_input==3:
      ll.search()
      print("\n")
    elif user_input==4:
      ll.display()
      print("\n")
  except ValueError as e:
      print("Invalid choice.\n")

  question=input("Enter y to continue and n to stop:")
  if(question=='n' or question=='N'):
    break
  else:
    continue

